--- #YAML:1.0
name:               UDT-Simple
version:            0.01
abstract:           simplified Perl bindings for UDT(reliable UDP based application level data transport protocol - http://udt.sourceforge.net/)
author:
    - borislav nikolov <jack@sofialondonmoskva.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
